version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: mongo

    ports:
      - "27017:27017"
      
    networks:
      - catalog    

  catalogapi:
    image: catalog-image
    container_name: catalogapi
    build: 
      context: .
      dockerfile: ./catalog/Catalog.API/Dockerfile
    
    depends_on:
      - catalogdb

    ports:
      - "5000:80"

    networks:
      - catalog

networks: 
  catalog: